language: go
go: '1.12'
env:
- GO111MODULE=on
install: go mod download
script: make ci
after_success: bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - $HOME/.cache/go-build
  - $HOME/gopath/pkg/mod
